In [1]:
import numpy as np
import scipy as sc
import opt_einsum as oe
from sys import getsizeof

a = np.random.rand(5)
print(a.shape,getsizeof(a))
a = a[np.newaxis,:,np.newaxis]
print(a.shape,getsizeof(a))
print(a)
print(np.zeros((1,5,1)))

(5,) 136
(1, 5, 1) 128
[[[ 0.10027431]
  [ 0.61864438]
  [ 0.90004867]
  [ 0.9991721 ]
  [ 0.62443983]]]
[[[ 0.]
  [ 0.]
  [ 0.]
  [ 0.]
  [ 0.]]]


In [14]:
len(a.shape)==a.ndim
b=np.array([5,])
b.size
print(a)
print(np.einsum("ijk->ij",a))
a,b=None,None

[[[ 0.10027431]
  [ 0.61864438]
  [ 0.90004867]
  [ 0.9991721 ]
  [ 0.62443983]]]
[[ 0.10027431  0.61864438  0.90004867  0.9991721   0.62443983]]


In [23]:
lista=[np.zeros((1,5,1))]*10
lista[2]

array([[[ 0.],
        [ 0.],
        [ 0.],
        [ 0.],
        [ 0.]]])

In [19]:
c = np.random.rand(5,5)
d = np.random.rand(5)

from scipy.linalg import svd
s = svd(c)
s[1]

array([ 2.75203221,  1.23596526,  0.69681136,  0.46965487,  0.01757523])

In [23]:
d4 = np.random.rand(3,4,5,6)

d3=d4.reshape(3,4,5*6)
d2 = d3.reshape(3*4,30)
#print(d2)
dims=np.array([12,30])
d1 = d4.reshape(dims)
d2==d1

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,

In [38]:
from math import factorial

def coherent(n,phi,dim):
    array = np.zeros(dim)
    for i in range(dim):
        array[i] = np.exp(-n/2)*(np.sqrt(n)*np.exp(phi))**i/np.sqrt(float(factorial(i)))
    return array
initenv    = np.zeros((1,7,1),complex)
initenv = coherent(.1,0,7)[np.newaxis,:,np.newaxis]
print(initenv.shape)
print(initenv)

(1, 7, 1)
[[[  9.51229425e-01]
  [  3.00805156e-01]
  [  6.72620777e-02]
  [  1.22803191e-02]
  [  1.94168893e-03]
  [  2.74596282e-04]
  [  3.54502276e-05]]]


In [40]:
initenv/np.sqrt(np.sum(initenv**2))

array([[[  9.51229425e-01],
        [  3.00805156e-01],
        [  6.72620777e-02],
        [  1.22803191e-02],
        [  1.94168893e-03],
        [  2.74596282e-04],
        [  3.54502276e-05]]])

In [47]:
a = np.random.rand(1,5,1)
print(a.size)
print(np.sum(a))
print(np.sum(a[0,:,0]))

5
2.08167392129
2.08167392129


In [50]:
dim_a,dim_initenv,dim_c = a.shape[1],initenv.shape[1],a.shape[1]
print(dim_a, dim_initenv,dim_c)

5 7 5


In [61]:
ind=2
text = None
b=a[0,:,:]
print(b.shape)

(5, 1)


In [63]:
a[0:1,2,0:1]

array([[ 0.9479183]])

In [103]:
from scipy.linalg import svd
b=np.random.rand(5)#np.array([1,0,0,0,0])#
b=b/np.sum(b)
c=np.random.rand(4)#np.array([0,0,0,1])#
c=c/np.sum(c)
d=np.tensordot(b,c,axes=0)
print(np.sum(d))
#d=d/np.sum(d)
svds=svd(d,full_matrices=False)
#print(svds)
e1=svds[0][:,:1]
e2 = np.diag(svds[1][:1])
e3 = svds[2][:1,:]
print(oe.contract("ij,jk,kl->il",e1,e2,e3))
print(d)
print(e1/b.reshape(b.size,1))
print(oe.contract("ij,jk",e2,e3)/c)

1.0
[[ 0.08496519  0.0533627   0.10238228  0.05629309]
 [ 0.01513643  0.00950649  0.01823926  0.01002853]
 [ 0.07788368  0.04891514  0.09384914  0.05160129]
 [ 0.06955452  0.04368398  0.08381257  0.04608286]
 [ 0.03853511  0.02420212  0.04643446  0.02553117]]
[[ 0.08496519  0.0533627   0.10238228  0.05629309]
 [ 0.01513643  0.00950649  0.01823926  0.01002853]
 [ 0.07788368  0.04891514  0.09384914  0.05160129]
 [ 0.06955452  0.04368398  0.08381257  0.04608286]
 [ 0.03853511  0.02420212  0.04643446  0.02553117]]
[[-2.03115684]
 [-2.03115684]
 [-2.03115684]
 [-2.03115684]
 [-2.03115684]]
[[-0.49233027 -0.49233027 -0.49233027 -0.49233027]]
