In [70]:
import numpy as np

indS = 4
indB = 2
B = np.ones(5)
F = np.ones(5)
S = np.ones(9)
B2 = np.zeros(5)
B2[indB] = 1
F2 = np.zeros(5)
F2[indB] = 1
S2 = np.zeros(9)
S2[indS] = 1
print(S)
state1 = np.einsum("i,j,k,l,m,n->ijklmn",F,S,B,F,S,B)
state2 = np.einsum("i,j,k,l,m,n->ijklmn",F2,S2,B2,F2,S2,B2)
dim_tS = S.shape[0]
M=0
es=np.einsum

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [71]:
def a(state,which,N):
    new_state = np.zeros(state.shape,complex)
    if dim_tS>2*N:
        n=np.linspace(N,int((dim_tS)/2),dim_tS-2*N).astype(np.int64)
        nprod = 1.
        i = 0
        while i<N:
            nprod *= np.sqrt(n-i)
            i+=1

        ich  = (-1)**(which+1)*(2*int(np.any(M))*(2-which)+which)#which=1->1/3, which=2->-2/-2
        iend = state.shape[ich]
        context = ["j,ijklmn->ijklmn","m,ijklmn->ijklmn","J,gIeJKhLfMN->gIeJKhLfMN","M,gIeJKhLfMN->gIeJKhLfMN"]

        idx=[slice(None)]*state.ndim
        idx[ich]=slice(None,iend-2*N)

        new_state[tuple(idx)] = es(context[which-1+int(np.any(M))*2],nprod,np.take(state,np.arange(2*N,iend),axis=ich))

    return new_state

print(state1[0,:,0,0,0,0])
print(a(state1,1,1)[0,:,0,0,0,0]**2)
print(state1[0,0,0,0,:,0])
print(a(state1,2,1)[0,0,0,0,:,0]**2)
print(state1[0,:,0,0,0,0])
print(a(state1,1,2)[0,:,0,0,0,0]**2)
print(state1[0,0,0,0,:,0])
print(a(state1,2,2)[0,0,0,0,:,0]**2)

print("\n")
print(state2[indB,:,indB,indB,indS,indB])
print(a(state2,1,1)[indB,:,indB,indB,indS,indB]**2)
print(state2[indB,indS,indB,indB,:,indB])
print(a(state2,2,1)[indB,indS,indB,indB,:,indB]**2)
print(state2[indB,:,indB,indB,indS,indB])
print(a(state2,1,2)[indB,:,indB,indB,indS,indB]**2)
print(state2[indB,indS,indB,indB,:,indB])
print(a(state2,2,2)[indB,indS,indB,indB,:,indB]**2)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.+0.j  1.+0.j  2.+0.j  2.+0.j  3.+0.j  3.+0.j  4.+0.j  0.+0.j  0.+0.j]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.+0.j  1.+0.j  2.+0.j  2.+0.j  3.+0.j  3.+0.j  4.+0.j  0.+0.j  0.+0.j]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
[  2.+0.j   2.+0.j   6.+0.j   6.+0.j  12.+0.j   0.+0.j   0.+0.j   0.+0.j
   0.+0.j]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
[  2.+0.j   2.+0.j   6.+0.j   6.+0.j  12.+0.j   0.+0.j   0.+0.j   0.+0.j
   0.+0.j]


[ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
[ 0.+0.j  0.+0.j  2.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
[ 0.+0.j  0.+0.j  2.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
[ 2.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
[ 2.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]


In [72]:
def ad(state,which,N):
    new_state = np.zeros(state.shape,complex)
    if dim_tS>2*N:
        n=np.linspace(N,int((dim_tS)/2),dim_tS-2*N).astype(np.int64)
        nprod = 1.
        i = 0
        while i<N:
            nprod *= np.sqrt(n-i)
            i+=1

        ich  = (-1)**(which+1)*(2*int(np.any(M))*(2-which)+which)#which=1->1/3, which=2->-2/-2
        iend = state.shape[ich]
        context = ["j,ijklmn->ijklmn","m,ijklmn->ijklmn","J,gIeJKhLfMN->gIeJKhLfMN","M,gIeJKhLfMN->gIeJKhLfMN"]

        idx=[slice(None)]*state.ndim
        idx[ich]=slice(2*N,iend)

        new_state[tuple(idx)] = es(context[which-1+int(np.any(M))*2],nprod,np.take(state,np.arange(iend-2*N),axis=ich))
    return new_state

print(state1[0,:,0,0,0,0])
print(ad(state1,1,1)[0,:,0,0,0,0]**2)
print(state1[0,0,0,0,:,0])
print(ad(state1,2,1)[0,0,0,0,:,0]**2)
print(state1[0,:,0,0,0,0])
print(ad(state1,1,2)[0,:,0,0,0,0]**2)
print(state1[0,0,0,0,:,0])
print(ad(state1,2,2)[0,0,0,0,:,0]**2)

print("\n")
print(state2[indB,:,indB,indB,indS,indB])
print(ad(state2,1,1)[indB,:,indB,indB,indS,indB]**2)
print(state2[indB,indS,indB,indB,:,indB])
print(ad(state2,2,1)[indB,indS,indB,indB,:,indB]**2)
print(state2[indB,:,indB,indB,indS,indB])
print(ad(state2,1,2)[indB,:,indB,indB,indS,indB]**2)
print(state2[indB,indS,indB,indB,:,indB])
print(ad(state2,2,2)[indB,indS,indB,indB,:,indB]**2)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 0.+0.j  0.+0.j  1.+0.j  1.+0.j  2.+0.j  2.+0.j  3.+0.j  3.+0.j  4.+0.j]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 0.+0.j  0.+0.j  1.+0.j  1.+0.j  2.+0.j  2.+0.j  3.+0.j  3.+0.j  4.+0.j]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
[  0.+0.j   0.+0.j   0.+0.j   0.+0.j   2.+0.j   2.+0.j   6.+0.j   6.+0.j
  12.+0.j]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
[  0.+0.j   0.+0.j   0.+0.j   0.+0.j   2.+0.j   2.+0.j   6.+0.j   6.+0.j
  12.+0.j]


[ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  3.+0.j  0.+0.j  0.+0.j]
[ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  3.+0.j  0.+0.j  0.+0.j]
[ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
[  0.+0.j   0.+0.j   0.+0.j   0.+0.j   0.+0.j   0.+0.j   0.+0.j   0.+0.j
  12.+0.j]
[ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
[  0.+0.j   0.+0.j   0.+0.j   0.+0.j   0.+0.j   0.+0.j   0.+0.j   0.+0.j
  12.+0.j]


In [73]:
def sm(state,which):
    new_state = np.zeros(state.shape,complex)
    ich  = (-1)**(which+1)*(2*int(np.any(M))*(2-which)+which)#which=1->1/3, which=2->-2/-2
    iend = state.shape[ich]

    idx=[slice(None)]*state.ndim
    idx[ich]=slice(0,dim_tS-1,2)

    new_state[tuple(idx)] = np.take(state,np.arange(1,dim_tS,2),axis=ich)
    return new_state
print(state1[0,:,0,0,0,0])
print(sm(state1,1)[0,:,0,0,0,0]**2)
print(state1[0,0,0,0,:,0])
print(sm(state1,2)[0,0,0,0,:,0]**2)

print("\n")
print(state2[indB,:,indB,indB,indS,indB])
print(sm(state2,1)[indB,:,indB,indB,indS,indB]**2)
print(state2[indB,indS,indB,indB,:,indB])
print(sm(state2,2)[indB,indS,indB,indB,:,indB]**2)


[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.+0.j  0.+0.j  1.+0.j  0.+0.j  1.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.+0.j  0.+0.j  1.+0.j  0.+0.j  1.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j]


[ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]


In [74]:
def sp(state,which):
    new_state = np.zeros(state.shape,complex)
    ich  = (-1)**(which+1)*(2*int(np.any(M))*(2-which)+which)#which=1->1/3, which=2->-2/-2
    iend = state.shape[ich]

    idx=[slice(None)]*state.ndim
    idx[ich]=slice(1,dim_tS,2)

    new_state[tuple(idx)] = np.take(state,np.arange(0,dim_tS-1,2),axis=ich)
    return new_state

print(state1[0,:,0,0,0,0])
print(sp(state1,1)[0,:,0,0,0,0]**2)
print(state1[0,0,0,0,:,0])
print(sp(state1,2)[0,0,0,0,:,0]**2)

print("\n")
print(state2[indB,:,indB,indB,indS,indB])
print(sp(state2,1)[indB,:,indB,indB,indS,indB]**2)
print(state2[indB,indS,indB,indB,:,indB])
print(sp(state2,2)[indB,indS,indB,indB,:,indB]**2)


[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 0.+0.j  1.+0.j  0.+0.j  1.+0.j  0.+0.j  1.+0.j  0.+0.j  1.+0.j  0.+0.j]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 0.+0.j  1.+0.j  0.+0.j  1.+0.j  0.+0.j  1.+0.j  0.+0.j  1.+0.j  0.+0.j]


[ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  1.+0.j  0.+0.j  0.+0.j  0.+0.j]


In [75]:
def JC(state,which):
    new_tS_g = np.zeros(state.shape,complex)
    new_tS_Ome = np.zeros(state.shape,complex)
    n = np.linspace(1,int((dim_tS)/2),dim_tS-2).astype(np.int64)
    n = np.sqrt(n[0:dim_tS-1:2])

    ich  = (-1)**(which+1)*(2*int(np.any(M))*(2-which)+which)#which=1->1/3, which=2->-2/-2
    iend = state.shape[ich]

    if g[which-1] != 0:
        context = ["j,ijklmn->ijklmn","m,ijklmn->ijklmn","J,gIeJKhLfMN->gIeJKhLfMN","M,gIeJKhLfMN->gIeJKhLfMN"]

        idx1=[slice(None)]*state.ndim
        idx2=[slice(None)]*state.ndim
        idx1[ich]=slice(1,dim_tS-1,2)
        idx2[ich]=slice(2,dim_tS,2)

        new_tS_g[tuple(idx1)] = es(context[which-1+int(np.any(M))*2],n*g[which-1],np.take(state,np.arange(2,dim_tS,2),axis=ich))
        new_tS_g[tuple(idx2)] = es(context[which-1+int(np.any(M))*2],n*g[which-1],np.take(state,np.arange(1,dim_tS-1,2),axis=ich))

    if Ome[which-1] != 0:
        idx1=[slice(None)]*state.ndim
        idx2=[slice(None)]*state.ndim
        idx1[ich]=slice(0,dim_tS-2,2)
        idx2[ich]=slice(1,dim_tS-1,2)

        new_tS_Ome[tuple(idx1)] = np.take(state,np.arange(1,dim_tS-1,2),axis=ich)
        new_tS_Ome[tuple(idx2)] = np.take(state,np.arange(0,dim_tS-2,2),axis=ich)
    return new_tS_g+new_tS_Ome

g=np.array([1,1])
Ome = np.array([0,0])

print(state1[0,:,0,0,0,0])
print(JC(state1,1)[0,:,0,0,0,0]**2)
print(state1[0,0,0,0,:,0])
print(JC(state1,2)[0,0,0,0,:,0]**2)

print("\n")
print(state2[indB,:,indB,indB,indS,indB])
print(JC(state2,1)[indB,:,indB,indB,indS,indB]**2)
print(state2[indB,indS,indB,indB,:,indB])
print(JC(state2,2)[indB,indS,indB,indB,:,indB]**2)


[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 0.+0.j  1.+0.j  1.+0.j  2.+0.j  2.+0.j  3.+0.j  3.+0.j  4.+0.j  4.+0.j]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 0.+0.j  1.+0.j  1.+0.j  2.+0.j  2.+0.j  3.+0.j  3.+0.j  4.+0.j  4.+0.j]


[ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
[ 0.+0.j  0.+0.j  0.+0.j  2.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
[ 0.+0.j  0.+0.j  0.+0.j  2.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]


In [76]:
def nc(state,which,const):
    n=np.linspace(0,int((dim_tS)/2),dim_tS).astype(np.int64)
    new_state = np.zeros(state.shape,complex)
    context = ["j,ijklmn->ijklmn","m,ijklmn->ijklmn","J,gIeJKhLfMN->gIeJKhLfMN","M,gIeJKhLfMN->gIeJKhLfMN"]

    new_state = es(context[which-1+int(np.any(M))*2],n+const,state)
    return new_state

print(state1[0,:,0,0,0,0])
print(nc(state1,1,0)[0,:,0,0,0,0])
print(state1[0,0,0,0,:,0])
print(nc(state1,2,0)[0,0,0,0,:,0])

print("\n")
print(state2[indB,:,indB,indB,indS,indB])
print(nc(state2,1,0)[indB,:,indB,indB,indS,indB])
print(state2[indB,indS,indB,indB,:,indB])
print(nc(state2,2,0)[indB,indS,indB,indB,:,indB])


[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 0.  0.  1.  1.  2.  2.  3.  3.  4.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 0.  0.  1.  1.  2.  2.  3.  3.  4.]


[ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  2.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  2.  0.  0.  0.  0.]


In [77]:
def MS(state,which):
    new_tS = np.zeros(state.shape,complex)
    new_tS += state
    if Dele[which-1] == 0:
        return -1j*dt*(C(state,which)+JC(state,which))
    else:
        ich  = (-1)**(which+1)*(2*int(np.any(M))*(2-which)+which)#which=1->1/3, which=2->-2/-2
        iend = state.shape[ich]

        idx=[slice(None)]*new_state.ndim
        idx[ich]=slice(0,dim_tS,2)

        new_state[tuple(idx)] = 0
        return -1j*dt*(C(state,which)+JC(state,which)+Dele[which-1]*new_tS)

dt = .01
Dele = np.array([0,0])
def C(state,which):
    return 0

print(state1[0,:,0,0,0,0])
print(MS(state1,1)[0,:,0,0,0,0]**2)
print(state1[0,0,0,0,:,0])
print(MS(state1,2)[0,0,0,0,:,0]**2)

print("\n")
print(state2[indB,:,indB,indB,indS,indB])
print(MS(state2,1)[indB,:,indB,indB,indS,indB]**2)
print(state2[indB,indS,indB,indB,:,indB])
print(MS(state2,2)[indB,indS,indB,indB,:,indB]**2)


[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 0.0000+0.j -0.0001-0.j -0.0001-0.j -0.0002-0.j -0.0002-0.j -0.0003-0.j
 -0.0003-0.j -0.0004-0.j -0.0004-0.j]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 0.0000+0.j -0.0001-0.j -0.0001-0.j -0.0002-0.j -0.0002-0.j -0.0003-0.j
 -0.0003-0.j -0.0004-0.j -0.0004-0.j]


[ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
[ 0.0000+0.j  0.0000+0.j  0.0000+0.j -0.0002-0.j  0.0000+0.j  0.0000+0.j
  0.0000+0.j  0.0000+0.j  0.0000+0.j]
[ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
[ 0.0000+0.j  0.0000+0.j  0.0000+0.j -0.0002-0.j  0.0000+0.j  0.0000+0.j
  0.0000+0.j  0.0000+0.j  0.0000+0.j]


In [78]:
def E(state,which,N):
    new_state_tB = np.zeros(state.shape,complex)
    new_state_tF = np.zeros(state.shape,complex)
    if N<state.shape[int(np.any(M)*2+2)]:
        n = np.arange(N,state.shape[int(np.any(M)*2+2)])
        nprod = 1.
        i = 0
        if M<L:
            phip=0.
        else:
            phip=phi
        while i<N:
            nprod *= np.sqrt(n-i)
            i+=1

        if gamma_B[which-1] > 0.:
            ich = (-1)**(which+1)*(int(np.any(M))*2*(2-which)+(3-which))#which=1->2/4, which=2->-1/-1
            iend = state.shape[ich]
            context = ["k,ijklmn->ijklmn","n,ijklmn->ijklmn","K,gIeJKhLfMN->gIeJKhLfMN","N,gIeJKhLfMN->gIeJKhLfMN"]

            idx=[slice(None)]*state.ndim
            idx[ich]=np.arange(0,iend-N)

#			print(new_state_tB[tuple(idx)].shape,np.take(state,np.arange(N,iend),axis=ich).shape,nprod.shape,N)
            new_state_tB[tuple(idx)] = es(context[which-1+int(np.any(M))*2],nprod*np.sqrt(gamma_B[which-1]*dt)**N,np.take(state,np.arange(N,iend),axis=ich))

        if gamma_F[which-1] > 0:
            ich = int(np.any(M))*(2-which)+(int(np.any(M))+3)*(1-which)#which=1->0/1, which=2->-3/-4
            iend = state.shape[ich]
            context = ["i,ijklmn->ijklmn","l,ijklmn->ijklmn","I,gIeJKhLfMN->gIeJKhLfMN","L,gIeJKhLfMN->gIeJKhLfMN"]

            idx=[slice(None)]*state.ndim
            idx[ich]=np.arange(0,iend-N)

#			print(new_state_tF[tuple(idx)].shape,np.take(state,np.arange(N,iend),axis=ich).shape,nprod.shape,N)
            new_state_tF[tuple(idx)] = es(context[which-1+int(np.any(M))*2],nprod*np.sqrt(gamma_F[which-1]*dt)**N,np.take(state,np.arange(N,iend),axis=ich))*np.exp(-1j*N*phip)

    return new_state_tB+new_state_tF

L=10

gamma_B = np.array([1,1])
gamma_F = np.array([1,1])

print(state1[:,0,0,0,0,0])
print(E(state1,1,1)[:,0,0,0,0,0]**2)
print(E(state1,1,2)[:,0,0,0,0,0]**2)
print(state1[0,0,:,0,0,0])
print(E(state1,1,1)[0,0,:,0,0,0]**2)
print(state1[0,0,0,:,0,0])
print(E(state1,2,1)[0,0,0,:,0,0]**2)
print(state1[0,0,0,0,0,:])
print(E(state1,2,1)[0,0,0,0,0,:]**2)
print(E(state1,2,2)[0,0,0,0,0,:]**2)

print("\n")
print(state2[:,indS,indB,indB,indS,indB])
print(E(state2,1,1)[:,indS,indB,indB,indS,indB]**2)
print(E(state2,1,1)[indB,indS,indB,:,indS,indB]**2)
print(E(state2,1,2)[:,indS,indB,indB,indS,indB]**2)
print(state2[indB,indS,:,indB,indS,indB])
print(E(state2,1,1)[indB,indS,:,indB,indS,indB]**2)
print(state2[indB,indS,indB,:,indS,indB])
print(E(state2,2,1)[indB,indS,indB,:,indS,indB]**2)
print(state2[indB,indS,indB,indB,indS,:])
print(E(state2,2,1)[indB,indS,indB,indB,indS,:]**2)
print(E(state2,2,2)[indB,indS,indB,indB,indS,:]**2)

[ 1.  1.  1.  1.  1.]
[ 0.04000000+0.j  0.05828427+0.j  0.07464102+0.j  0.09000000+0.j
  0.01000000+0.j]
[ 0.00080000+0.j  0.00149282+0.j  0.00237980+0.j  0.00020000+0.j
  0.00020000+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.04000000+0.j  0.05828427+0.j  0.07464102+0.j  0.09000000+0.j
  0.01000000+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.04000000+0.j  0.05828427+0.j  0.07464102+0.j  0.09000000+0.j
  0.01000000+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.04000000+0.j  0.05828427+0.j  0.07464102+0.j  0.09000000+0.j
  0.01000000+0.j]
[ 0.00080000+0.j  0.00149282+0.j  0.00237980+0.j  0.00020000+0.j
  0.00020000+0.j]


[ 0.  0.  1.  0.  0.]
[ 0.00+0.j  0.02+0.j  0.00+0.j  0.00+0.j  0.00+0.j]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 0.0002+0.j  0.0000+0.j  0.0000+0.j  0.0000+0.j  0.0000+0.j]
[ 0.  0.  1.  0.  0.]
[ 0.00+0.j  0.02+0.j  0.00+0.j  0.00+0.j  0.00+0.j]
[ 0.  0.  1.  0.  0.]
[ 0.00+0.j  0.02+0.j  0.00+0.j  0.00+0.j  0.00+0.j]
[ 0.  0.  1.  0.  0.]
[ 0.00+0.j  0.02+0.j  0.00+0.j  0.00+0.j  0.00+0.j]
[ 0.0002+0.j

In [79]:
def Ed(state,which,N):
    new_state_tB = np.zeros(state.shape,complex)
    new_state_tF = np.zeros(state.shape,complex)
    if N<state.shape[int(np.any(M)*2+2)]:
        n = np.arange(N,state.shape[int(np.any(M)*2+2)])
        nprod = 1.
        i = 0
        if M<L:
            phip=0.
        else:
            phip=phi
        while i<N:
            nprod *= np.sqrt(n-i)
            i+=1

        if gamma_B[which-1] > 0.:
            ich = (-1)**(which+1)*(int(np.any(M))*2*(2-which)+(3-which))#which=1->2/4, which=2->-1/-1
            iend = state.shape[ich]
            context = ["k,ijklmn->ijklmn","n,ijklmn->ijklmn","K,gIeJKhLfMN->gIeJKhLfMN","N,gIeJKhLfMN->gIeJKhLfMN"]

            idx=[slice(None)]*state.ndim
            idx[ich]=slice(N,iend)
#			print("context:", context[which-1+int(np.any(M))*2],", which:", which,", M:", M)
            new_state_tB[tuple(idx)] = es(context[which-1+int(np.any(M))*2],nprod*np.sqrt(gamma_B[which-1]*dt)**N,np.take(state,np.arange(0,iend-N),axis=ich))

        if gamma_F[which-1] > 0:
            ich = int(np.any(M))*(2-which)+(int(np.any(M))+3)*(1-which)#which=1->0/1, which=2->-3/-4
            iend = state.shape[ich]
            context = ["i,ijklmn->ijklmn","l,ijklmn->ijklmn","I,gIeJKhLfMN->gIeJKhLfMN","L,gIeJKhLfMN->gIeJKhLfMN"]

            idx=[slice(None)]*state.ndim
            idx[ich]=slice(N,iend)

            new_state_tF[tuple(idx)] = es(context[which-1+int(np.any(M))*2],nprod*np.sqrt(gamma_F[which-1]*dt)**N,np.take(state,np.arange(0,iend-N),axis=ich))*np.exp(1j*N*phip)

    return new_state_tB+new_state_tF


L=10

gamma_B = np.array([1,1])
gamma_F = np.array([1,1])

print(state1[:,0,0,0,0,0])
print(Ed(state1,1,1)[:,0,0,0,0,0]**2)
print(Ed(state1,1,2)[:,0,0,0,0,0]**2)
print(state1[0,0,:,0,0,0])
print(Ed(state1,1,1)[0,0,:,0,0,0]**2)
print(state1[0,0,0,:,0,0])
print(Ed(state1,2,1)[0,0,0,:,0,0]**2)
print(state1[0,0,0,0,0,:])
print(Ed(state1,2,1)[0,0,0,0,0,:]**2)
print(Ed(state1,2,2)[0,0,0,0,0,:]**2)

print("\n")
print(state2[:,indS,indB,indB,indS,indB])
print(Ed(state2,1,1)[:,indS,indB,indB,indS,indB]**2)
print(Ed(state2,1,1)[indB,indS,indB,:,indS,indB]**2)
print(Ed(state2,1,2)[:,indS,indB,indB,indS,indB]**2)
print(state2[indB,indS,:,indB,indS,indB])
print(Ed(state2,1,1)[indB,indS,:,indB,indS,indB]**2)
print(state2[indB,indS,indB,:,indS,indB])
print(Ed(state2,2,1)[indB,indS,indB,:,indS,indB]**2)
print(state2[indB,indS,indB,indB,indS,:])
print(Ed(state2,2,1)[indB,indS,indB,indB,indS,:]**2)
print(Ed(state2,2,2)[indB,indS,indB,indB,indS,:]**2)

[ 1.  1.  1.  1.  1.]
[ 0.00+0.j  0.01+0.j  0.02+0.j  0.03+0.j  0.04+0.j]
[ 0.0000+0.j  0.0000+0.j  0.0002+0.j  0.0006+0.j  0.0012+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.00+0.j  0.01+0.j  0.02+0.j  0.03+0.j  0.04+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.00+0.j  0.01+0.j  0.02+0.j  0.03+0.j  0.04+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.00+0.j  0.01+0.j  0.02+0.j  0.03+0.j  0.04+0.j]
[ 0.0000+0.j  0.0000+0.j  0.0002+0.j  0.0006+0.j  0.0012+0.j]


[ 0.  0.  1.  0.  0.]
[ 0.00+0.j  0.00+0.j  0.00+0.j  0.03+0.j  0.00+0.j]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 0.0000+0.j  0.0000+0.j  0.0000+0.j  0.0000+0.j  0.0012+0.j]
[ 0.  0.  1.  0.  0.]
[ 0.00+0.j  0.00+0.j  0.00+0.j  0.03+0.j  0.00+0.j]
[ 0.  0.  1.  0.  0.]
[ 0.00+0.j  0.00+0.j  0.00+0.j  0.03+0.j  0.00+0.j]
[ 0.  0.  1.  0.  0.]
[ 0.00+0.j  0.00+0.j  0.00+0.j  0.03+0.j  0.00+0.j]
[ 0.0000+0.j  0.0000+0.j  0.0000+0.j  0.0000+0.j  0.0012+0.j]


In [83]:
from opt_einsum import contract
def E2mix(state,which):
    new_state_mix = np.zeros(state.shape,complex)
    if 2<state.shape[int(np.any(M)*2+2)]:
        if M<L:
            phip=0.
        else:
            phip=phi
        n = np.sqrt(np.arange(1,state.shape[int(np.any(M)*2+2)]))
        if gamma_B[which-1]>0 and gamma_F[which-1]>0:
            ich1 = (-1)**(which+1)*(int(np.any(M))*2*(2-which)+(3-which))#which=1->2/4, which=2->-1/-1
            ich2 = int(np.any(M))*(2-which)+(int(np.any(M))+3)*(1-which)#which=1->0/1, which=2->-3/-4
            iend1 = state.shape[ich1]
            iend2 = state.shape[ich2]
            context = ["i,k,ijklmn->ijklmn","l,n,ijklmn->ijklmn","I,K,gIeJKhLfMN->gIeJKhLfMN","L,N,gIeJKhLfMN->gIeJKhLfMN"]

            idx_n=[slice(None)]*state.ndim
            idx_n[ich1]=slice(None,iend1-1)
            idx_n[ich2]=slice(None,iend2-1)
            idx_o=[slice(None)]*state.ndim
            idx_o[ich1]=slice(1,iend1)
            idx_o[ich2]=slice(1,iend2)

            new_state_mix[tuple(idx_n)] = (np.sqrt(gamma_B[which-1]*gamma_F[which-1])*np.exp(-1j*phip)*dt*
                            contract(context[which-1+int(np.any(M))*2],n,n,state[tuple(idx_o)]))
    return 2*new_state_mix

print(state1[:,0,0,0,0,0])
print(E2mix(state1,1)[:,0,0,0,0,0])
print(state1[0,0,:,0,0,0])
print(E2mix(state1,1)[0,0,:,0,0,0])
print(state1[0,0,0,:,0,0])
print(E2mix(state1,2)[0,0,0,:,0,0])
print(state1[0,0,0,0,0,:])
print(E2mix(state1,2)[0,0,0,0,0,:])

print("\n")
print(state2[:,indS,indB,indB,indS,indB])
print(E2mix(state2,1)[:,indS,indB-1,indB,indS,indB])
print(E2mix(state2,1)[indB,indS,indB,:,indS,indB-1])
print(state2[indB,indS,:,indB,indS,indB])
print(E2mix(state2,1)[indB-1,indS,:,indB,indS,indB])
print(state2[indB,indS,indB-1,:,indS,indB])
print(E2mix(state2,2)[indB,indS,indB,:,indS,indB-1])
print(state2[indB,indS,indB,indB,indS,:])
print(E2mix(state2,2)[indB,indS,indB,indB-1,indS,:])


[ 1.  1.  1.  1.  1.]
[ 0.02000000+0.j  0.02828427+0.j  0.03464102+0.j  0.04000000+0.j
  0.00000000+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.02000000+0.j  0.02828427+0.j  0.03464102+0.j  0.04000000+0.j
  0.00000000+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.02000000+0.j  0.02828427+0.j  0.03464102+0.j  0.04000000+0.j
  0.00000000+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.02000000+0.j  0.02828427+0.j  0.03464102+0.j  0.04000000+0.j
  0.00000000+0.j]


[ 0.  0.  1.  0.  0.]
[ 0.00+0.j  0.04+0.j  0.00+0.j  0.00+0.j  0.00+0.j]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 0.  0.  1.  0.  0.]
[ 0.00+0.j  0.04+0.j  0.00+0.j  0.00+0.j  0.00+0.j]
[ 0.  0.  0.  0.  0.]
[ 0.00+0.j  0.04+0.j  0.00+0.j  0.00+0.j  0.00+0.j]
[ 0.  0.  1.  0.  0.]
[ 0.00+0.j  0.04+0.j  0.00+0.j  0.00+0.j  0.00+0.j]


In [85]:
from opt_einsum import contract
def Ed2mix(state,which):
    new_state_mix = np.zeros(state.shape,complex)
    if 2<state.shape[int(np.any(M)*2+2)]:
        if M<L:
            phip=0.
        else:
            phip=phi
        n = np.sqrt(np.arange(1,state.shape[int(np.any(M)*2+2)]))
        if gamma_B[which-1]>0 and gamma_F[which-1]>0:

            ich1 = (-1)**(which+1)*(int(np.any(M))*2*(2-which)+(3-which))#which=1->2/4, which=2->-1/-1
            ich2 = int(np.any(M))*(2-which)+(int(np.any(M))+3)*(1-which)#which=1->0/1, which=2->-3/-4
            iend1 = state.shape[ich1]
            iend2 = state.shape[ich2]
            context = ["i,k,ijklmn->ijklmn","l,n,ijklmn->ijklmn","I,K,gIeJKhLfMN->gIeJKhLfMN","L,N,gIeJKhLfMN->gIeJKhLfMN"]

            idx_o=[slice(None)]*state.ndim
            idx_o[ich1]=slice(None,iend1-1)
            idx_o[ich2]=slice(None,iend2-1)
            idx_n=[slice(None)]*state.ndim
            idx_n[ich1]=slice(1,iend1)
            idx_n[ich2]=slice(1,iend2)

            new_state_mix[tuple(idx_n)] = (np.sqrt(gamma_B[which-1]*gamma_F[which-1])*np.exp(1j*phip)*dt*
                            contract(context[which-1+int(np.any(M))*2],n,n,state[tuple(idx_o)]))
    return 2*new_state_mix

print(state1[:,0,0,0,0,0])
print(Ed2mix(state1,1)[:,0,0,0,0,0])
print(state1[0,0,:,0,0,0])
print(Ed2mix(state1,1)[0,0,:,0,0,0])
print(state1[0,0,0,:,0,0])
print(Ed2mix(state1,2)[0,0,0,:,0,0])
print(state1[0,0,0,0,0,:])
print(Ed2mix(state1,2)[0,0,0,0,0,:])

print("\n")
print(state2[:,indS,indB,indB,indS,indB])
print(Ed2mix(state2,1)[:,indS,indB+1,indB,indS,indB])
print(Ed2mix(state2,1)[indB,indS,indB,:,indS,indB+1])
print(state2[indB,indS,:,indB,indS,indB])
print(Ed2mix(state2,1)[indB+1,indS,:,indB,indS,indB])
print(state2[indB,indS,indB+1,:,indS,indB])
print(Ed2mix(state2,2)[indB,indS,indB,:,indS,indB+1])
print(state2[indB,indS,indB,indB,indS,:])
print(Ed2mix(state2,2)[indB,indS,indB,indB+1,indS,:])


[ 1.  1.  1.  1.  1.]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]


[ 0.  0.  1.  0.  0.]
[ 0.00+0.j  0.00+0.j  0.00+0.j  0.06+0.j  0.00+0.j]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 0.  0.  1.  0.  0.]
[ 0.00+0.j  0.00+0.j  0.00+0.j  0.06+0.j  0.00+0.j]
[ 0.  0.  0.  0.  0.]
[ 0.00+0.j  0.00+0.j  0.00+0.j  0.06+0.j  0.00+0.j]
[ 0.  0.  1.  0.  0.]
[ 0.00+0.j  0.00+0.j  0.00+0.j  0.06+0.j  0.00+0.j]


In [89]:
def E3mix(state,which):

    new_state_mix1 = np.zeros(state.shape,complex)
    new_state_mix2 = np.zeros(state.shape,complex)
    if 2<state.shape[int(np.any(M)*2+2)]:
        if M<L:
            phip=0.
        else:
            phip=phi
        n = np.arange(1,state.shape[int(np.any(M)*2+2)])
        n2 = np.sqrt(n[1:]*(n[1:]-1))
        n = np.sqrt(n)
        if gamma_B[which-1]>0 and gamma_F[which-1]>0:
            ich1 = (-1)**(which+1)*(int(np.any(M))*2*(2-which)+(3-which))#which=1->2/4, which=2->-1/-1
            ich2 = int(np.any(M))*(2-which)+(int(np.any(M))+3)*(1-which)#which=1->0/1, which=2->-3/-4
            iend1 = state.shape[ich1]
            iend2 = state.shape[ich2]
            context = ["i,k,ijklmn->ijklmn","l,n,ijklmn->ijklmn","I,K,gIeJKhLfMN->gIeJKhLfMN","L,N,gIeJKhLfMN->gIeJKhLfMN"]

            idx_n1=[slice(None)]*state.ndim
            idx_n1[ich1]=slice(None,iend1-1)
            idx_n1[ich2]=slice(None,iend2-2)
            idx_n2=[slice(None)]*state.ndim
            idx_n2[ich1]=slice(None,iend1-2)
            idx_n2[ich2]=slice(None,iend2-1)
            idx_o1=[slice(None)]*state.ndim
            idx_o1[ich1]=slice(1,iend1)
            idx_o1[ich2]=slice(2,iend2)
            idx_o2=[slice(None)]*state.ndim
            idx_o2[ich1]=slice(2,iend1)
            idx_o2[ich2]=slice(1,iend2)

            new_state_mix1[tuple(idx_n1)] = (gamma_F[which-1]*np.sqrt(gamma_B[which-1])*dt**1.5*np.exp(-2j*phip)*
                            contract(context[which-1+int(np.any(M))*2],n2,n,state[tuple(idx_o1)]))
            new_state_mix2[tuple(idx_n2)] = (gamma_B[which-1]*np.sqrt(gamma_F[which-1])*dt**1.5*np.exp(-1j*phip)*
                            contract(context[which-1+int(np.any(M))*2],n,n2,state[tuple(idx_o2)]))
    return 3*(new_state_mix1+new_state_mix2)

print(state1[:,0,0,0,0,0])
print(E3mix(state1,1)[:,0,0,0,0,0])
print(state1[0,0,:,0,0,0])
print(E3mix(state1,1)[0,0,:,0,0,0])
print(state1[0,0,0,:,0,0])
print(E3mix(state1,2)[0,0,0,:,0,0])
print(state1[0,0,0,0,0,:])
print(E3mix(state1,2)[0,0,0,0,0,:])

print("\n")
print(state2[:,indS,indB,indB,indS,indB])
print(E3mix(state2,1)[:,indS,indB-2,indB,indS,indB])
print(E3mix(state2,1)[indB,indS,indB,:,indS,indB-2])
print(state2[indB,indS,:,indB,indS,indB])
print(E3mix(state2,1)[indB-1,indS,:,indB,indS,indB])
print(state2[indB,indS,indB,:,indS,indB])
print(E3mix(state2,2)[indB,indS,indB,:,indS,indB-1])
print(state2[indB,indS,indB,indB,indS,:])
print(E3mix(state2,2)[indB,indS,indB,indB-2,indS,:])


[ 1.  1.  1.  1.  1.]
[ 0.00848528+0.j  0.01334847+0.j  0.01774077+0.j  0.00848528+0.j
  0.00000000+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.00848528+0.j  0.01334847+0.j  0.01774077+0.j  0.00848528+0.j
  0.00000000+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.00848528+0.j  0.01334847+0.j  0.01774077+0.j  0.00848528+0.j
  0.00000000+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.00848528+0.j  0.01334847+0.j  0.01774077+0.j  0.00848528+0.j
  0.00000000+0.j]


[ 0.  0.  1.  0.  0.]
[ 0.000+0.j  0.006+0.j  0.000+0.j  0.000+0.j  0.000+0.j]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 0.  0.  1.  0.  0.]
[ 0.006+0.j  0.000+0.j  0.000+0.j  0.000+0.j  0.000+0.j]
[ 0.  0.  1.  0.  0.]
[ 0.006+0.j  0.000+0.j  0.000+0.j  0.000+0.j  0.000+0.j]
[ 0.  0.  1.  0.  0.]
[ 0.000+0.j  0.006+0.j  0.000+0.j  0.000+0.j  0.000+0.j]


In [91]:
def Ed3mix(state,which):

    new_state_mix1 = np.zeros(state.shape,complex)
    new_state_mix2 = np.zeros(state.shape,complex)
    if 2<state.shape[int(np.any(M)*2+2)]:
        if M<L:
            phip=0.
        else:
            phip=phi
        n = np.arange(1,state.shape[int(np.any(M)*2+2)])
        n2 = np.sqrt(n[1:]*(n[1:]-1))
        n = np.sqrt(n)
        if gamma_B[which-1]>0 and gamma_F[which-1]>0:
            ich1 = (-1)**(which+1)*(int(np.any(M))*2*(2-which)+(3-which))#which=1->2/4, which=2->-1/-1
            ich2 = int(np.any(M))*(2-which)+(int(np.any(M))+3)*(1-which)#which=1->0/1, which=2->-3/-4
            iend1 = state.shape[ich1]
            iend2 = state.shape[ich2]
            context = ["i,k,ijklmn->ijklmn","l,n,ijklmn->ijklmn","I,K,gIeJKhLfMN->gIeJKhLfMN","L,N,gIeJKhLfMN->gIeJKhLfMN"]

            idx_o1=[slice(None)]*state.ndim
            idx_o1[ich1]=slice(None,iend1-1)
            idx_o1[ich2]=slice(None,iend2-2)
            idx_o2=[slice(None)]*state.ndim
            idx_o2[ich1]=slice(None,iend1-2)
            idx_o2[ich2]=slice(None,iend2-1)
            idx_n1=[slice(None)]*state.ndim
            idx_n1[ich1]=slice(1,iend1)
            idx_n1[ich2]=slice(2,iend2)
            idx_n2=[slice(None)]*state.ndim
            idx_n2[ich1]=slice(2,iend1)
            idx_n2[ich2]=slice(1,iend2)

            new_state_mix1[tuple(idx_n1)] = (gamma_F[which-1]*np.sqrt(gamma_B[which-1])*dt**1.5*np.exp(2j*phip)*
                            contract(context[which-1+int(np.any(M))*2],n2,n,state[tuple(idx_o1)]))
            new_state_mix2[tuple(idx_n2)] = (gamma_B[which-1]*np.sqrt(gamma_F[which-1])*dt**1.5*np.exp(1j*phip)*
                            contract(context[which-1+int(np.any(M))*2],n,n2,state[tuple(idx_o2)]))

    return 3*(new_state_mix1+new_state_mix2)

print(state1[:,0,0,0,0,0])
print(Ed3mix(state1,1)[:,0,0,0,0,0])
print(state1[0,0,:,0,0,0])
print(Ed3mix(state1,1)[0,0,:,0,0,0])
print(state1[0,0,0,:,0,0])
print(Ed3mix(state1,2)[0,0,0,:,0,0])
print(state1[0,0,0,0,0,:])
print(Ed3mix(state1,2)[0,0,0,0,0,:])

print("\n")
print(state2[:,indS,indB,indB,indS,indB])
print(Ed3mix(state2,1)[:,indS,indB+2,indB,indS,indB])
print(Ed3mix(state2,1)[indB,indS,indB,:,indS,indB+2])
print(state2[indB,indS,:,indB,indS,indB])
print(Ed3mix(state2,1)[indB+1,indS,:,indB,indS,indB])
print(state2[indB,indS,indB,:,indS,indB])
print(Ed3mix(state2,2)[indB,indS,indB,:,indS,indB+1])
print(state2[indB,indS,indB,indB,indS,:])
print(Ed3mix(state2,2)[indB,indS,indB,indB+2,indS,:])


[ 1.  1.  1.  1.  1.]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]


[ 0.  0.  1.  0.  0.]
[ 0.000+0.j  0.000+0.j  0.000+0.j  0.018+0.j  0.000+0.j]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 0.  0.  1.  0.  0.]
[ 0.000+0.j  0.000+0.j  0.000+0.j  0.000+0.j  0.018+0.j]
[ 0.  0.  1.  0.  0.]
[ 0.000+0.j  0.000+0.j  0.000+0.j  0.000+0.j  0.018+0.j]
[ 0.  0.  1.  0.  0.]
[ 0.000+0.j  0.000+0.j  0.000+0.j  0.018+0.j  0.000+0.j]


In [102]:
import numpy as np

indS = 4
indB = 2
B = np.ones(5)
F = np.ones(5)
S = np.ones(9)
B2 = np.zeros(5)
B2[indB] = 1
F2 = np.zeros(5)
F2[indB] = 1
S2 = np.zeros(9)
S2[indS] = 1
print(S)
state1 = np.einsum("i,j,k,l,m,n->ijklmn",F,S,B,F,S,B)
state2 = np.einsum("i,j,k,l,m,n->ijklmn",F2,S2,B2,F2,S2,B2)
dim_tS = S.shape[0]
M=0
es=np.einsum

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [96]:
def E4mix(state,which):

    new_state_mix1 = np.zeros(state.shape,complex)
    new_state_mix2 = np.zeros(state.shape,complex)
    new_state_mix3 = np.zeros(state.shape,complex)

    if 2<state.shape[int(np.any(M)*2+2)]:
        if M<L:
            phip=0.
        else:
            phip=phi
        n = np.arange(1,state.shape[int(np.any(M)*2+2)])
        n2 = np.sqrt(n[1:]*(n[1:]-1))
        if 3<state.shape[int(np.any(M)*2+2)]:
            n3 = np.sqrt(n[2:]*(n[2:]-1)*(n[2:]-2))
        n = np.sqrt(n)
        if gamma_B[which-1]>0 and gamma_F[which-1]>0:
            ich1 = (-1)**(which+1)*(int(np.any(M))*2*(2-which)+(3-which))#which=1->2/4, which=2->-1/-1
            ich2 = int(np.any(M))*(2-which)+(int(np.any(M))+3)*(1-which)#which=1->0/1, which=2->-3/-4
            iend1 = state.shape[ich1]
            iend2 = state.shape[ich2]
            context = ["i,k,ijklmn->ijklmn","l,n,ijklmn->ijklmn","I,K,gIeJKhLfMN->gIeJKhLfMN","L,N,gIeJKhLfMN->gIeJKhLfMN"]

            if 3<state.shape[int(np.any(M)*2+2)]:
                idx_n1=[slice(None)]*state.ndim
                idx_n1[ich1]=slice(None,iend1-3)
                idx_n1[ich2]=slice(None,iend2-1)
                idx_n2=[slice(None)]*state.ndim
                idx_n2[ich1]=slice(None,iend1-1)
                idx_n2[ich2]=slice(None,iend2-3)
                idx_o1=[slice(None)]*state.ndim
                idx_o1[ich1]=slice(3,iend1)
                idx_o1[ich2]=slice(1,iend2)
                idx_o2=[slice(None)]*state.ndim
                idx_o2[ich1]=slice(1,iend1)
                idx_o2[ich2]=slice(3,iend2)
                new_state_mix1[tuple(idx_n1)] = (gamma_B[which-1]*np.sqrt(gamma_B[which-1]*gamma_F[which-1])*dt**2*np.exp(-1j*phip)*
                                contract(context[which-1+int(np.any(M))*2],n,n3,state[tuple(idx_o1)]))
                new_state_mix2[tuple(idx_n2)] = (gamma_F[which-1]*np.sqrt(gamma_F[which-1]*gamma_B[which-1])*dt**2*np.exp(-3j*phip)*
                                contract(context[which-1+int(np.any(M))*2],n3,n,state[tuple(idx_o2)]))
            idx_n3=[slice(None)]*state.ndim
            idx_n3[ich1]=slice(None,iend1-2)
            idx_n3[ich2]=slice(None,iend2-2)
            idx_o3=[slice(None)]*state.ndim
            idx_o3[ich1]=slice(2,iend1)
            idx_o3[ich2]=slice(2,iend2)

            new_state_mix3[tuple(idx_n3)] = (gamma_B[which-1]*gamma_F[which-1]*dt**2*np.exp(-2j*phip)*
                            contract(context[which-1+int(np.any(M))*2],n2,n2,state[tuple(idx_o3)]))

    return 4*(new_state_mix1+new_state_mix2)+6*new_state_mix3

print(state1[:,0,0,0,0,0])
print(E4mix(state1,1)[:,0,0,0,0,0])
print(state1[0,0,:,0,0,0])
print(E4mix(state1,1)[0,0,:,0,0,0])
print(state1[0,0,0,:,0,0])
print(E4mix(state1,2)[0,0,0,:,0,0])
print(state1[0,0,0,0,0,:])
print(E4mix(state1,2)[0,0,0,0,0,:])

print("\n")
print(state2[:,indS,indB,indB,indS,indB])
print(E4mix(state2,1)[:,indS,indB-3,indB,indS,indB])
print(E4mix(state2,1)[indB,indS,indB,:,indS,indB-3])
print(state2[indB,indS,:,indB,indS,indB])
print(E4mix(state2,1)[indB-2,indS,:,indB,indS,indB])
print(state2[indB,indS,indB,:,indS,indB])
print(E4mix(state2,2)[indB,indS,indB,:,indS,indB-1])
print(state2[indB,indS,indB,indB,indS,:])
print(E4mix(state2,2)[indB,indS,indB,indB-2,indS,:])

[ 1.  1.  1.  1.  1.]
[ 0.00315959+0.j  0.00542369+0.j  0.00463644+0.j  0.00195959+0.j
  0.00000000+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.00315959+0.j  0.00542369+0.j  0.00463644+0.j  0.00195959+0.j
  0.00000000+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.00315959+0.j  0.00542369+0.j  0.00463644+0.j  0.00195959+0.j
  0.00000000+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.00315959+0.j  0.00542369+0.j  0.00463644+0.j  0.00195959+0.j
  0.00000000+0.j]


[ 0.  0.  0.  0.  1.]
[ 0.00000000+0.j  0.00000000+0.j  0.00000000+0.j  0.00391918+0.j
  0.00000000+0.j]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 0.  0.  0.  0.  1.]
[ 0.0000+0.j  0.0000+0.j  0.0072+0.j  0.0000+0.j  0.0000+0.j]
[ 0.  0.  0.  0.  1.]
[ 0.00000000+0.j  0.00391918+0.j  0.00000000+0.j  0.00000000+0.j
  0.00000000+0.j]
[ 0.  0.  0.  0.  1.]
[ 0.0000+0.j  0.0000+0.j  0.0072+0.j  0.0000+0.j  0.0000+0.j]


In [101]:
def Ed4mix(state,which):
    new_state_mix1 = np.zeros(state.shape,complex)
    new_state_mix2 = np.zeros(state.shape,complex)
    new_state_mix3 = np.zeros(state.shape,complex)
    if 2<state.shape[int(np.any(M)*2+2)]:
        if M<L:
            phip=0.
        else:
            phip=phi
        n = np.arange(1,state.shape[int(np.any(M)*2+2)])
        n2 = np.sqrt(n[1:]*(n[1:]-1))
        if 3<state.shape[int(np.any(M)*2+2)]:
            n3 = np.sqrt(n[2:]*(n[2:]-1)*(n[2:]-2))
        n = np.sqrt(n)
        if gamma_B[which-1]>0 and gamma_F[which-1]>0:
            ich1 = (-1)**(which+1)*(int(np.any(M))*2*(2-which)+(3-which))#which=1->2/4, which=2->-1/-1
            ich2 = int(np.any(M))*(2-which)+(int(np.any(M))+3)*(1-which)#which=1->0/1, which=2->-3/-4
            iend1 = state.shape[ich1]
            iend2 = state.shape[ich2]
            context = ["i,k,ijklmn->ijklmn","l,n,ijklmn->ijklmn","I,K,gIeJKhLfMN->gIeJKhLfMN","L,N,gIeJKhLfMN->gIeJKhLfMN"]

            if 3<state.shape[int(np.any(M)*2+2)]:
                idx_o1=[slice(None)]*state.ndim
                idx_o1[ich1]=slice(None,iend1-3)
                idx_o1[ich2]=slice(None,iend2-1)
                idx_o2=[slice(None)]*state.ndim
                idx_o2[ich1]=slice(None,iend1-1)
                idx_o2[ich2]=slice(None,iend2-3)
                idx_n1=[slice(None)]*state.ndim
                idx_n1[ich1]=slice(3,iend1)
                idx_n1[ich2]=slice(1,iend2)
                idx_n2=[slice(None)]*state.ndim
                idx_n2[ich1]=slice(1,iend1)
                idx_n2[ich2]=slice(3,iend2)
                new_state_mix1[tuple(idx_n1)] = (gamma_B[which-1]*np.sqrt(gamma_B[which-1]*gamma_F[which-1])*dt**2*np.exp(1j*phip)*
                                contract(context[which-1+int(np.any(M))*2],n,n3,state[tuple(idx_o1)]))
                new_state_mix2[tuple(idx_n2)] = (gamma_F[which-1]*np.sqrt(gamma_F[which-1]*gamma_B[which-1])*dt**2*np.exp(3j*phip)*
                                contract(context[which-1+int(np.any(M))*2],n3,n,state[tuple(idx_o2)]))
            idx_o3=[slice(None)]*state.ndim
            idx_o3[ich1]=slice(None,iend1-2)
            idx_o3[ich2]=slice(None,iend2-2)
            idx_n3=[slice(None)]*state.ndim
            idx_n3[ich1]=slice(2,iend1)
            idx_n3[ich2]=slice(2,iend2)

            new_state_mix3[tuple(idx_n3)] = (gamma_B[which-1]*gamma_F[which-1]*dt**2*np.exp(2j*phip)*
                            contract(context[which-1+int(np.any(M))*2],n2,n2,state[tuple(idx_o3)]))

    return 4*(new_state_mix1+new_state_mix2)+6*new_state_mix3

print(state1[:,0,0,0,0,0])
print(Ed4mix(state1,1)[:,0,0,0,0,0])
print(state1[0,0,:,0,0,0])
print(Ed4mix(state1,1)[0,0,:,0,0,0])
print(state1[0,0,0,:,0,0])
print(Ed4mix(state1,2)[0,0,0,:,0,0])
print(state1[0,0,0,0,0,:])
print(Ed4mix(state1,2)[0,0,0,0,0,:])

print("\n")
print(state2[:,indS,indB,indB,indS,indB])
print(Ed4mix(state2,1)[:,indS,indB+3,indB,indS,indB])
print(Ed4mix(state2,1)[indB,indS,indB,:,indS,indB+3])
print(state2[indB,indS,:,indB,indS,indB])
print(Ed4mix(state2,1)[indB+2,indS,:,indB,indS,indB])
print(state2[indB,indS,indB,:,indS,indB])
print(Ed4mix(state2,2)[indB,indS,indB,:,indS,indB+1])
print(state2[indB,indS,indB,indB,indS,:])
print(Ed4mix(state2,2)[indB,indS,indB,indB+2,indS,:])

[ 1.  1.  1.  1.  1.]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]


[ 1.  0.  0.  0.  0.]
[ 0.0000000+0.j  0.0009798+0.j  0.0000000+0.j  0.0000000+0.j  0.0000000+0.j]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 1.  0.  0.  0.  0.]
[ 0.0000+0.j  0.0000+0.j  0.0012+0.j  0.0000+0.j  0.0000+0.j]
[ 1.  0.  0.  0.  0.]
[ 0.0000000+0.j  0.0000000+0.j  0.0000000+0.j  0.0009798+0.j  0.0000000+0.j]
[ 1.  0.  0.  0.  0.]
[ 0.0000+0.j  0.0000+0.j  0.0012+0.j  0.0000+0.j  0.0000+0.j]


In [119]:
def nE(state,which,const):
    new_state_tF = np.zeros(state.shape,complex)
    new_state_tB = np.zeros(state.shape,complex)
    new_state_tFB1 = np.zeros(state.shape,complex)
    new_state_tFB2 = np.zeros(state.shape,complex)
    n = np.arange(0,state.shape[-1])
    if gamma_F[which-1]>0:
        context = ["i,ijklmn->ijklmn","l,ijklmn->ijklmn","I,gIeJKhLfMN->gIeJKhLfMN","L,gIeJKhLfMN->gIeJKhLfMN"]

        new_state_tF = dt*gamma_F[which-1]*es(context[which-1+2*int(np.any(M))],n+const,state)

    if gamma_B[which-1]>0:
        context = ["k,ijklmn->ijklmn","n,ijklmn->ijklmn","K,gIeJKhLfMN->gIeJKhLfMN","N,gIeJKhLfMN->gIeJKhLfMN"]

        new_state_tB = dt*gamma_B[which-1]*es(context[which-1+2*int(np.any(M))],n+const,state)

    if gamma_B[which-1]>0 and gamma_F[which-1]>0:

        if M<L:
            phip=0.
        else:
            phip=phi

        context = ["i,k,ijklmn->ijklmn","l,n,ijklmn->ijklmn","I,K,gIeJKhLfMN->gIeJKhLfMN","L,N,gIeJKhLfMN->gIeJKhLfMN"]
        ich1 = (-1)**(which+1)*(int(np.any(M))*2*(2-which)+(3-which))#which=1->2/4, which=2->-1/-1
        ich2 = int(np.any(M))*(2-which)+(int(np.any(M))+3)*(1-which)#which=1->0/1, which=2->-3/-4
        iend1 = state.shape[ich1]
        iend2 = state.shape[ich2]
        n = np.sqrt(n[1:])

        idx_n1=[slice(None)]*state.ndim
        idx_n1[ich1]=slice(None,iend1-1)
        idx_n1[ich2]=slice(1,iend2)
        idx_n2=[slice(None)]*state.ndim
        idx_n2[ich1]=slice(1,iend1)
        idx_n2[ich2]=slice(None,iend2-1)
        idx_o1=[slice(None)]*state.ndim
        idx_o1[ich1]=slice(1,iend1)
        idx_o1[ich2]=slice(None,iend2-1)
        idx_o2=[slice(None)]*state.ndim
        idx_o2[ich1]=slice(None,iend1-1)
        idx_o2[ich2]=slice(1,iend2)

        new_state_tFB1[tuple(idx_n1)] = (np.sqrt(gamma_F[which-1]*gamma_B[which-1])*dt*np.exp(1j*phip)*
                        contract(context[which-1+int(np.any(M))*2],n,n,state[tuple(idx_o1)]))
        new_state_tFB2[tuple(idx_n2)] = (np.sqrt(gamma_F[which-1]*gamma_B[which-1])*dt*np.exp(-1j*phip)*
                        contract(context[which-1+int(np.any(M))*2],n,n,state[tuple(idx_o2)]))
        

    return new_state_tF+new_state_tB+new_state_tFB1+new_state_tFB2

print(state1[:,0,0,0,0,0])
print(nE(state1,1,0)[:,0,1,1,0,1])
print(state1[0,0,:,0,0,0])
print(nE(state1,1,0)[1,0,:,1,0,1])
print(state1[0,0,0,:,0,0])
print(nE(state1,2,0)[1,0,1,:,0,1])
print(state1[0,0,0,0,0,:])
print(nE(state1,2,0)[1,0,1,1,0,:])

print("\n")
print(state2[:,indS,indB,indB,indS,indB])
print(nE(state2,1,0)[:,indS,indB-1,indB,indS,indB])
print(nE(state2,1,0)[indB,indS,indB+1,:,indS,indB])
print(state2[indB,indS,:,indB,indS,indB])
print(nE(state2,1,1)[indB,indS,:,indB,indS,indB])
print(state2[indB,indS,indB,:,indS,indB])
print(nE(state2,2,2)[indB,indS,indB,:,indS,indB])
print(state2[indB,indS,indB,indB,indS,:])
print(nE(state2,2,0)[indB,indS,indB,indB,indS,:])

[ 1.  1.  1.  1.  1.]
[ 0.02000000+0.j  0.04828427+0.j  0.06732051+0.j  0.08449490+0.j
  0.07828427+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.02000000+0.j  0.04828427+0.j  0.06732051+0.j  0.08449490+0.j
  0.07828427+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.02000000+0.j  0.04828427+0.j  0.06732051+0.j  0.08449490+0.j
  0.07828427+0.j]
[ 1.  1.  1.  1.  1.]
[ 0.02000000+0.j  0.04828427+0.j  0.06732051+0.j  0.08449490+0.j
  0.07828427+0.j]


[ 0.  0.  1.  0.  0.]
[ 0.0000000+0.j  0.0000000+0.j  0.0000000+0.j  0.0244949+0.j  0.0000000+0.j]
[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
[ 0.  0.  1.  0.  0.]
[ 0.00+0.j  0.00+0.j  0.06+0.j  0.00+0.j  0.00+0.j]
[ 0.  0.  1.  0.  0.]
[ 0.00+0.j  0.00+0.j  0.08+0.j  0.00+0.j  0.00+0.j]
[ 0.  0.  1.  0.  0.]
[ 0.00+0.j  0.00+0.j  0.04+0.j  0.00+0.j  0.00+0.j]
